apiVersion: apps/v1
kind: Deployment
metadata:
  name: central
  namespace: distribuidas-conjunta
spec:
  replicas: 1
  selector:
    matchLabels:
      app: central
  template:
    metadata:
      labels:
        app: central
    spec:
      initContainers:
        - name: wait-for-postgresql
          image: busybox:1.35
          command:
            - sh
            - -c
            - until nc -z postgresql-service.distribuidas-conjunta.svc.cluster.local 5432; do sleep 5; done
        - name: wait-for-rabbitmq
          image: busybox:1.35
          command:
            - sh
            - -c
            - until nc -z rabbitmq-service.distribuidas-conjunta.svc.cluster.local 5672; do sleep 5; done
      containers:
        - name: central
          image: central:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: SERVER_PORT
              value: "8000"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgresql-service.distribuidas-conjunta.svc.cluster.local:5432/central_db"
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: postgresql-config
                  key: POSTGRES_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql-secret
                  key: POSTGRES_PASSWORD
            - name: SPRING_RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: rabbitmq-config
                  key: RABBITMQ_HOST
            - name: SPRING_RABBITMQ_PORT
              valueFrom:
                configMapKeyRef:
                  name: rabbitmq-config
                  key: RABBITMQ_PORT
            - name: SPRING_RABBITMQ_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: rabbitmq-config
                  key: RABBITMQ_USERNAME
            - name: SPRING_RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: RABBITMQ_PASSWORD
            - name: JPA_HIBERNATE_DDL_AUTO
              value: "update"
            - name: HIBERNATE_SHOW_SQL
              value: "true"
            - name: HIBERNATE_FORMAT_SQL
              value: "true"
            - name: HIBERNATE_USE_SQL_COMMENTS
              value: "true"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8000
            initialDelaySeconds: 60
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8000
            initialDelaySeconds: 120
            periodSeconds: 15
