apiVersion: v1
kind: Service
metadata:
  name: central
  namespace: distribuidas-conjunta
spec:
  type: ClusterIP
  selector:
    app: central
  ports:
    - name: http
      port: 8000
      targetPort: 8000
